name: weather_app_tutorial
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.3.4 <4.0.0'

dependencies:
  dio: ^5.4.3+1
  flutter:
    sdk: flutter
  flutter_riverpod: ^2.5.1
  geolocator: ^12.0.0
  jiffy: ^6.3.1
  permission_handler: ^11.3.1
  firebase_auth: ^5.1.1
  firebase_core: ^3.1.1
  cloud_firestore: ^5.0.2
  carousel_slider: ^4.2.1
  flutter_osm_plugin: ^1.1.0
  flutter_local_notifications: ^17.2.1+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/icons/
    - assets/tips/cloud1.png
    - assets/tips/cloud2.png
    - assets/tips/cloud3.png
    - assets/tips/cloud4.png
    - assets/tips/cloud5.png
    - assets/tips/w1.png
    - assets/tips/w2.png
    - assets/tips/w3.png
    - assets/tips/w4.png
    - assets/tips/w5.png
    - assets/tips/em1.png
    - assets/tips/em2.png
    - assets/tips/em3.png





  #   - images/a_dot_ham.jpeg